# Generated by Django 4.2.5 on 2023-09-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='is_customer',
            field=models.BooleanField(default=False, verbose_name='customer'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_seller',
            field=models.BooleanField(default=False, verbose_name='seller'),
        ),
    ]
