# Generated by Django 4.2.5 on 2023-09-25 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_productvariant_variant_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WAOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(editable=False, max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=30)),
                ('alternate_phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.TextField()),
                ('landmark', models.CharField(max_length=255)),
                ('extra', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_product', to='products.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='order/')),
                ('waorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.waorder')),
            ],
        ),
    ]
