# Generated by Django 4.2.5 on 2023-10-07 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waorder',
            name='pincode',
            field=models.CharField(default='623529', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waorder',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waorder',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extrainformation',
            name='waorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_info', to='orders.waorder'),
        ),
        migrations.AlterField(
            model_name='waorder',
            name='extra',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='waorder',
            name='landmark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
