# Generated by Django 4.2.5 on 2023-10-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_waorder_pincode_waorder_price_waorder_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainformation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='order/'),
        ),
    ]
