# Generated by Django 4.2.5 on 2023-10-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
