# Generated by Django 4.2.5 on 2023-09-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_gst_productvariant_type_variantspecification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='material',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='size',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='weight',
        ),
        migrations.AddField(
            model_name='category',
            name='decription',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='category',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
