# Generated by Django 4.2.5 on 2023-09-30 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productvariant_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variantspecification',
            old_name='product',
            new_name='variant',
        ),
    ]
